language: python
python:
    - 3.7
install:
  - pip install codecov
  - pip install pytest-cov
  - pip install jsonschema
  - pip install requests
script:
  - pytest tests --cov=validator
after_success:
  - codecov