language: python
python:
    - 3.7
install:
  - pip install codecov
  - pip install pytest-cov
  - pip install jsonschema
  - pip install requests
  - pip install gemmi
script:
  - pytest tests --cov=funpdbe_validator
after_success:
  - codecov